### ISSUE TITLE
Issue after setting up the DB

### ISSUE THREAD

**Issue by hazzzard** [Clansuite/Clansuite#19]
After cloning, installing the vendors and running through the installation steps, exactly after entering DB details, I get this error:

Fatal error: Interface 'Koch\Config\Adapter\AdapterInterface' not found in \Clansuite\vendor\ksst\kf\framework\Koch\Config\Adapter\INI.php on line 31

**Comment by jakoch** [comment]
Hey "hazzard"!

This might be a framework issue. The AdapterInterface is in the same namespace
I think, a use statement is not needed here, in order to load the interface.
So, it might be an autoloading problem or (if i'm wrong) a missing use statement.

https://github.com/KSST/KF/blob/master/framework/Koch/Config/Adapter/INI.php#L30
https://github.com/KSST/KF/tree/master/framework/Koch/Config/Adapter

Feel free to debug and patch this. A pull request is welcome!

Regards, Jens
